name: Deploy Storybook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install and Build
        run: |
          npm ci
          npm run build-storybook
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@da91e73
        with:
          branch: gh-pages
          folder: storybook-static
